version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:winner@db:3306/ResultSphere

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=winner
      - MYSQL_DATABASE=ResultSphere
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init-scripts:/docker-entrypoint-initdb.d

volumes:
  mysql-data: