version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=winner
      - DB_NAME=ResultSphere

  db:
    build: ./mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=winner
      - MYSQL_DATABASE=ResultSphere
      - MYSQL_USER=root
      - MYSQL_PASSWORD=winner
